name: CI

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      runs-on: 'ubuntu-latest'
      platform: 1234

    steps:
      - name: 'Show message'
      run: |
        echo 'Hello from GitHub Actions!'

      - name 'Showing env'
      run: |
      echo 'Platform: ${{ env.platform }}'
      echo 'Runs on: ${{ env.runs-on }}'
      