name: CI

on:
  push:
    branches: ['main']

jobs:
  build:
    env:
      runs: ubuntu-latest
      platform: 1234

    runs-on: ubuntu-latest

    steps:
      - name: 'Show message'
        run: echo 'Hello from GitHub Actions!'

      - name: 'Showing env'
        run: |
          echo 'Platform: ${{ env.platform }}'
          echo 'Runs on: ${{ env.runs }}'
